{% set name = "chemlite" %}
{% set version = "2.9.0" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 8070465b851e671c9acb1ffd664a5e5cbb6f168f17f12fb4a4ccf1a2f56fd134

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} setup.py install

requirements:
  host:
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - brs_utils

test:
  source_files:
    - tests
  imports:
    - chemlite
  requires:
    - pytest
  commands:
    - cd tests
    - pytest -v

about:
  home: https://github.com/brsynth/chemlite
  summary: Basic representation of compounds, reactions, pathways
  license: MIT
  license_file: LICENSE
  doc_url: https://brsynth.github.io/chemlite
  dev_url: https://github.com/brsynth/chemlite

extra:
  recipe-maintainers:
    - breakthewall
    - ramez17khaled
