{% set name = "chemlite" %}
{% set version = "2.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/{{ name }}/archive/{{ version }}.tar.gz
  sha256: b7529b9ba34926eb51b45f43cff6574e5810fe396a70f0693f5aa0921b7b7f49

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - brs_utils

test:
  source_files:
    - tests
  imports:
    - chemlite
  requires:
    - pytest
  commands:
    - cd tests
    - pytest -v

about:
  home: https://github.com/brsynth/chemlite
  summary: "Basic representation of compounds, reactions, pathways"
  license: MIT
  license_file: LICENSE
  doc_url: https://brsynth.github.io/chemlite
  dev_url: https://github.com/brsynth/chemlite

extra:
  recipe-maintainers:
    - breakthewall
